# coding: utf8
#!/usr/bin/python
'''
# 1 - RUN:
sudo openpyn --init

# Run this script
openpyn au -a paris
'''

import argparse
from actu_class import ActuClass


def main():
    # security
    auth_pass = '62f2b54421635099efe491ae13f56b37'

    ##############
    # defaults
    ##############
    # general config items
    config_path = './demo-configs'

    # DB storage folder (CSV + IMAGES)
    db_storage_csv = './outputs/posts/'
    db_storage_image = './outputs/images/'

    parser = argparse.ArgumentParser(
        description="Extract with ultscan",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument('-pw', '--password', help='Password to pass security layer')
    parser.add_argument('-dc', '--dir-config', help='Relative or absolute directory of configs')
    parser.add_argument('-dsc', '--dir-store-csv', help='Relative or absolute directory of csv storage')
    parser.add_argument('-dsi', '--dir-store-image', help='Relative or absolute directory of image storage')
    args = parser.parse_args()

    ##############
    # args override defaults
    ##############
    if not args.password or (args.password and not args.password == auth_pass):
        print('Unauthorized access ! Abording...')
        exit()

    if args.dir_config:
        config_path = args.dir_config
        config_path = config_path[:len(config_path)-1] if config_path.endswith('/') else config_path

    if args.dir_store_csv:
        db_storage_csv = args.dir_store_csv
        db_storage_csv = db_storage_csv[:len(db_storage_csv)-1] if db_storage_csv.endswith('/') else db_storage_csv
    if args.dir_store_image:
        db_storage_image = args.dir_store_image
        db_storage_image = db_storage_image[:len(db_storage_image)-1] if db_storage_image.endswith('/') else db_storage_image

    ##############
    # authorized and secure run
    # @TODO
    ##############

    test_model = {
        "batch_id": "jamaity-all",
        "orgs": "",
        "rubrique_website": "all",
        "default_pagination_limit": 1,
        "themes": "",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 975,
        "page_actu_home": "https://jamaity.org/forsa/",
        "page_actu_loop": "https://jamaity.org/forsa/page/ACTU_NBR/",
        "reg_ul": ".container .masonry-container",
        "reg_li": ".col-md-4.item",
        "reg_li_a": "a",
        "reg_li_title": "a::text",
        "reg_li_date": False,
        "reg_li_image": False,
        "single_title": False,
        "single_content": "#details .text-preview",
        "single_image": "img.event-img-big::attr(src)",
        "single_date": "meta[name='date']::attr(content)",
        "single_date_format": "timestamp",
        "single_tags": False,
        "deadline": ".row.clearfix > div.col-md-3.col-sm-3.col-xs-12.no-margin > p",
        "deadline_format": "%d%m%Y",
        "apply_url": False,
        "document_url": False,
        "document_title": False
    }

    '''
    test_model = {
        "batch_id": "jamaity",
        "orgs": "",
        "rubrique_website": "culture",
        "default_pagination_limit": 1,
        "themes": "culture",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 9,
        "page_actu_home": "https://jamaity.org/forsa/?type=all&region=tunisie&theme=arts-culture",
        "page_actu_loop": "https://jamaity.org/forsa/page/ACTU_NBR/?type=all&region=tunisie&theme=arts-culture",
        "reg_ul": ".container .masonry-container",
        "reg_li": ".col-md-4.item",
        "reg_li_a": "a",
        "reg_li_title": "a::text",
        "reg_li_date": False,
        "reg_li_image": False,
        "single_title": False,
        "single_content": "#details .text-preview",
        "single_image": "img.event-img-big::attr(src)",
        "single_date": "meta[name='date']::attr(content)",
        "single_date_format": "timestamp",
        "single_tags": False,
        "deadline": ".row.clearfix > div.col-md-3.col-sm-3.col-xs-12.no-margin > p",
        "deadline_format": "%d%m%Y",
        "apply_url": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "onthemove-news",
        "orgs": "",
        "rubrique_website": "culture",
        "default_pagination_limit": 1,
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 0,
        "loop_step": 1,
        "loop_end": 6,
        "page_actu_home": "https://on-the-move.org/news",
        "page_actu_loop": "https://on-the-move.org/news?sort_by=created&page=ACTU_NBR",
        "reg_ul": ".results--with-filters ul.no-style",
        "reg_li": "li.list",
        "reg_li_a": "a.list-link",
        "reg_li_title": ".list_title .block-title::text",
        "reg_li_date": False,
        "reg_li_image": False,
        "single_title": False,
        "single_content": "#block-otm-content",
        "single_image": ".image--centre-col picture img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": ".container dl.info dd time.datetime",
        "deadline_format": "%d%m%Y",
        "apply_url": False,
        "document_url": False,
        "document_title": False
    }

    test_model =  {
        "batch_id": "khaleejesque-ar",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "AR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 5,
        "page_actu_home": "https://khaleejesque.me/ar/",
        "page_actu_loop": "https://khaleejesque.me/ar/page/ACTU_NBR/",
        "reg_ul": "#main",
        "reg_li": "article.entry-preview",
        "reg_li_a": "h2.entry-title a",
        "reg_li_title": "h2.entry-title a::text",
        "reg_li_date": False,
        "reg_li_image": "img.wp-post-image::attr(src)",
        "single_title": "h1.entry-title::text",
        "single_content": "div.entry-content",
        "single_image": False,
        "single_date": 'li.meta-date::text',
        "single_date_format": False,
        "single_date_format": "%d%m%Y",
        # "single_date_format": "%Y%m%d",
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": "div.entry-content a:last-child::attr(href)",
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False,
    }

    test_model =  {
        "batch_id": "fundsforngos",
        "orgs": "",
        "rubrique_website": "opportunities", 
        "default_pagination_limit": "",
        "themes": "",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 3753,
        "page_actu_home": "https://www2.fundsforngos.org/",
        "page_actu_loop": "https://www2.fundsforngos.org/page/ACTU_NBR/",
        "reg_ul": "main#genesis-content",
        "reg_li": "article.post",
        "reg_li_a": "header.entry-header h4.entry-title a",
        "reg_li_title": "header.entry-header h4.entry-title a::text",
        "reg_li_date": False,
        "reg_li_image": "img.entry-image::attr(src)",
        "single_title": "h1.entry-title::text",
        "single_content": "main#genesis-content article.post",
        "single_image": "img.entry-image::attr(src)",
        "single_date": "meta[property='article:published_time']::attr(content)",
        "single_date_format": "%Y-%m-%dT%H:%M:%S%z",
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": "div.entry-content a:last-child::attr(href)",
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False,
    }

    test_model =  {
        "batch_id": "netex-general",
        "orgs": "",
        "rubrique_website": "open-calls",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 51,
        "page_actu_home": "https://netex.nmartproject.net/?cat=3",
        "page_actu_loop": "https://netex.nmartproject.net/?cat=3&paged=ACTU_NBR",
        "reg_ul": "#post-entry div.post-entry-inner",
        "reg_li": "article.post",
        "reg_li_a": "h2.post-title a",
        "reg_li_title": "h2.post-title a::text",
        "reg_li_date": ".post-meta span.entry-date abbr::attr(title)",
        "reg_li_image": ".post-thumb a img::attr(src)",
        "single_title": "#post-entry h1.post-title.entry-title::text",
        "single_content": "#post-entry .post-content .entry-content",
        "single_image": False,
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": ".post-content .entry-content p:first-child",
        "deadline_format": False,
        "apply_url": "#post-entry .post-content .entry-content a",
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }
    '''

    '''
    test_model =  {
        "batch_id": "transartists",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 0,
        "loop_step": 1,
        "loop_end": 49,
        "page_actu_home": "https://www.transartists.org/en/transartists-calls",
        "page_actu_loop": "https://www.transartists.org/en/transartists-calls?page=ACTU_NBR",
        "reg_ul": "table.table",
        "reg_li": "tr",
        "reg_li_a": "h2 a",
        "reg_li_title": "h2 a::text",
        "reg_li_date": False,
        "reg_li_image": False,
        "single_title": "div h2::text",
        "single_content": "div.field--name-field-body",
        "single_image": "img.image-style-teaser::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": "article .field__item a",
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }


    test_model = {
        "batch_id": "callfor-org",
        "orgs": "",
        "rubrique_website": "culture",
        "default_pagination_limit": 1,
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 3,
        "page_actu_home": "https://www.callfor.org/",
        "page_actu_loop": "https://www.callfor.org/page/ACTU_NBR/",
        "reg_ul": "#aligner",
        "reg_li": ".post.thickbox",
        "reg_li_a": ".posttitle a",
        "reg_li_title": ".posttitle a::text",
        "reg_li_date": False,
        "reg_li_image": ".entrywhole .entry img::attr(src)",
        "single_title": False,
        "single_content": ".entrywhole",
        "single_image": False,
        "single_date": False,
        "single_date_format": False,
        "single_tags": "#cattag a::text",
        "deadline": ".postdate_single",
        "deadline_format": "%d.%m.%Y",
        "apply_url": False,
        "guess_apply_url_last_url": True,
        "document_url": False,
        "document_title": False
    }
    test_model = {
        "batch_id": "resartis",
        "orgs": "",
        "rubrique_website": "culture",
        "default_pagination_limit": 2,
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 2,
        "page_actu_home": "https://resartis.org/open-calls/",
        "page_actu_loop": "https://resartis.org/open-calls/?fwp_paged=ACTU_NBR",
        "reg_ul": "#posts-container",
        "reg_li": "#posts-container .card__content",
        "reg_li_a": ".card__content h2.card__title a",
        "reg_li_title": ".card__content h2.card__title",
        "reg_li_date": ".card__content dt",
        "reg_li_image": "aside.card__image",
        "single_title": "h1.entry-title",
        "single_content": ".entry-content",
        "single_image": "header.entry-header .entry-featured",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": ".widget-area--post .section-wrap span",
        "deadline_format": "%Y-%m-%d",
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "document_url": False,
        "document_title": False,
    }

    test_model = {
        "batch_id": "culture360",
        "orgs": "",
        "rubrique_website": "open-calls",
        "default_pagination_limit": 3,
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://culture360.asef.org/opportunities/open_calls",
        "page_actu_loop": "https://culture360.asef.org/opportunities/open_calls/?page=ACTU_NBR",
        "reg_ul": ".col-xl-9.col-l-9.col-md-9.col-12 .row",
        "reg_li": ".col-xl-4.col-lg-4.col-md-4.col-sm-12.col-12.mb-3.col-print-4",
        "reg_li_a": ".padded-span a",
        "reg_li_title": ".title span.item-title::text",
        "reg_li_date": False,
        "reg_li_image": ".img-wrapper img.img-responsive::attr(src)",
        "single_title": ".item-image-title item-opportunities h1 span.item-title::text",
        "single_content": ".col-md-9.col-12.order-1.order-md-2",
        "single_image": ".item-image-title item-opportunities img.item-cover-img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": ".item-header .date",
        "deadline_format": "%d%m%Y",
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "document_url": False,
        "document_title": False,
    }
    
    test_model = {
        "batch_id": "institut-francais-tunisie",
        "orgs": "",
        "rubrique_website": "open-calls",
        "default_pagination_limit": 2,
        "themes": "education",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "http://www.institutfrancais-tunisie.com/appels-projets/",
        "page_actu_loop": "http://www.institutfrancais-tunisie.com/appels-projets?field_categorie_target_id=All&page=ACTU_NBR#/",
        "reg_ul": ".view-content .quicktabs-wrapper",
        "reg_li": ".views-row",
        "reg_li_a": ".views-field-title a",
        "reg_li_title": ".views-field-title a::text",
        "reg_li_date": ".views-field-published-at span.field-content",
        "reg_li_image": "a img.img-responsive::attr(src)",
        "single_title": ".titre_page h1.page-header span::text",
        "single_content": "#detail-body",
        "single_image": "#baniere img.img-responsive::attr(src)",
        "single_date": False,
        "single_date_format": "%d%m%Y-%H:%M",
        "single_tags": ".field.field--name-field-mots-cles-appels::text",
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "document_url": ".field--items.field--item span.file.file--mime-application-pdf.file--application-pdf.icon-before span.file-link a",
        "document_title": ".field--items.field--item span.file.file--mime-application-pdf.file--application-pdf.icon-before span.file-link a::text",
    }
    
    test_model = {
        "batch_id": "tunisie-concours",
        "orgs": "",
        "rubrique_website": "",
        "default_pagination_limit": "",
        "themes": "emploi",
        "lang": "AR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 264,
        "page_actu_home": "https://tunisieconcours.tn/",
        "page_actu_loop": "https://tunisieconcours.tn/page/ACTU_NBR/",
        "reg_ul": "main#main .generate-columns-container",
        "reg_li": "article.post.type-post",
        "reg_li_a": "h2.entry-title a",
        "reg_li_title": "h2.entry-title a::text",
        "reg_li_date": "time.entry-date.published",
        "reg_li_image": False,
        "single_title": False,
        "single_content": "#main .entry-content",
        "single_image": ".inside-article .featured-image.page-header-image-single img::attr(src)",
        "single_date": False,
        "single_date_format": "%d/%m/%Y",
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": ".entry-content a.wp-block-button__link::attr(href)",
        "guess_apply_url_last_url": False,
        "document_url": False,
        "document_title": False,
    }
    '''
    
    '''
    test_model = {
        "batch_id": "contemporaryand",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 4,
        "page_actu_home": "https://contemporaryand.com/opportunities/",
        "page_actu_loop": "https://contemporaryand.com/opportunities/page/ACTU_NBR/?currentstat=past",
        "reg_ul": "#content .row",
        "reg_li": ".col-lg-3.col-md-3.col-sm-6.col-xs-12",
        "reg_li_a": "h3.u2630 a",
        "reg_li_title": "h3.u2630 a::text",
        "reg_li_date": False,
        "reg_li_image": False,
        "single_title": ".container.col-md-12.inhalt h2::text",
        "single_content": ".col-lg-11.col-md-11.col-sm-11.col-xs-11.inhalt",
        "single_image": "figure.fixedratio img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": "span.oppdate",
        "deadline_format": "%d%m%Y",
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": "li.download a.file",
        "document_title": False
    }
    
    test_model = {
        "batch_id": "contemporaryand",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 4,
        "page_actu_home": "https://contemporaryand.com/opportunities/",
        "page_actu_loop": "https://contemporaryand.com/opportunities/page/ACTU_NBR/?currentstat=past",
        "reg_ul": "#content .row",
        "reg_li": ".col-lg-3.col-md-3.col-sm-6.col-xs-12",
        "reg_li_a": "h3.u2630 a",
        "reg_li_title": "h3.u2630 a::text",
        "reg_li_date": False,
        "reg_li_image": False,
        "single_title": ".container.col-md-12.inhalt h2::text",
        "single_content": ".col-lg-11.col-md-11.col-sm-11.col-xs-11.inhalt",
        "single_image": "figure.fixedratio img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": "span.oppdate",
        "deadline_format": "%d%m%Y",
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": "li.download a.file",
        "document_title": False
    }
    
    test_model = {
        "batch_id": "eeas",
        "orgs": "",
        "rubrique_website": "open-calls",
        "default_pagination_limit": 2,
        "themes": "",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 2,
        "page_actu_home": "https://www.eeas.europa.eu/eeas/tenders_en?f%5B0%5D=tender_site%3AEEAS&f%5B1%5D=tender_site%3AEEAS",
        "page_actu_loop": "https://www.eeas.europa.eu/eeas/tenders_en?f%5B0%5D=tender_site%3AEEAS&f%5B1%5D=tender_site%3AEEAS&page=ACTU_NBR",
        "reg_ul": ".related-grid",
        "reg_li": ".card.node",
        "reg_li_a": "h5.card-title a",
        "reg_li_title": "h5.card-title a::text",
        "reg_li_date": False,
        "reg_li_image": False,
        "single_title": "h1.field.field--name-title",
        "single_content": ".clearfix.text-formatted.field.field--name-field-text",
        "single_image": False,
        "single_date": ".content-header .node__meta",
        "single_date_format": "%d.%m.%Y",
        "single_tags": False,
        "deadline": ".field.field--name-field-deadline.field--type-datetime.field--label-hidden.field__item time::attr(datetime)",
        "deadline_format": "%Y-%m-%d",
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }
    
    # failed: access issue
    test_model = {
        "batch_id": "institut-francais-pro",
        "orgs": "",
        "rubrique_website": "open-calls",
        "default_pagination_limit": 8,
        "themes": "education",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 0,
        "loop_step": 1,
        "loop_end": 2,
        "page_actu_home": "https://www.pro.institutfrancais.com/fr/institut-francais/offre",
        "page_actu_loop": "https://www.pro.institutfrancais.com/fr/offre?page=ACTU_NBR",
        "reg_ul": ".content-main-list",
        "reg_li": "article.node.node--type-programme-formation.node--promoted.node--view-mode-search-index-specific",
        "reg_li_a": "h3.card-title a",
        "reg_li_title": "h3.card-title a::text",
        "reg_li_date": ".card-date .date p",
        "reg_li_image": "article .card-top article img::attr(src)",
        "single_title": "h1.title::text",
        "single_content": ".wrapper-zone-appel-candidature",
        "single_image": "article.media.media--type-image.media--view-mode-home-if-slider-paralax picture img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": ".wrapper-infos .field.field--name-field-thematiques.field--type-entity-reference.field--label-hidden.field__items",
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "culture-partnership",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 2,
        "loop_step": 1,
        "loop_end": 2,
        "page_actu_home": "https://www.culturepartnership.eu/en/opportunities",
        "page_actu_loop": "https://www.culturepartnership.eu/en/opportunities/page_ACTU_NBR",
        "reg_ul": "section.topic-list.news-list",
        "reg_li": ".row.inside-container .newslist-item-withfoto",
        "reg_li_a": "h1.title a",
        "reg_li_title": "h1.title a::text",
        "reg_li_date": False,
        "reg_li_image": ".row a.news-list-figure.col-md-6.col-sm-6.col-xs-6.col-xxs-12 img::attr(src)",
        "single_title": "h1.article-title.inner-wr::text",
        "single_content": "section.main_review.editor",
        "single_image": ".inside-container header.article-header.row .article-main-figure.col-md-6 img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": "section.main_review.editor a",
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "artwork-archive",
        "orgs": "",
        "rubrique_website": "call-for-enty",
        "default_pagination_limit": "",
        "themes": "education",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 2,
        "page_actu_home": "https://www.artworkarchive.com/call-for-entry",
        "page_actu_loop": "https://www.artworkarchive.com/call-for-entry?page=ACTU_NBR",
        "reg_ul": "#opportunity-list .row",
        "reg_li": ".medium-12.columns",
        "reg_li_a": ".medium-12.columns a",
        "reg_li_title": "h2::text",
        "reg_li_date": False,
        "reg_li_image": ".pull-left img::attr(src)",
        "single_title": "#call.row.medium-10.medium-offset-1.columns.call-hero-container.row.medium-6.columns h2::text",
        "single_content": ".small-12.columns section.external_link_security",
        "single_image": ".call-hero-container.row.medium-6.columns img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": "p.call-date",
        "deadline_format": False,
        "apply_url": ".pull-right.external-call-links a::attr(href)",
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
       "batch_id": "art-rabbit",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://www.artrabbit.com/artist-opportunities",
        "page_actu_loop": "https://www.artrabbit.com/artist-opportunities",
        "reg_ul": "#artopps",
        "reg_li": ".artopp",
        "reg_li_a": ".l_section h2 a",
        "reg_li_title": ".l_section h2 a::text",
        "reg_li_date": "l_section p.b_date",
        "reg_li_image": False,
        "single_title": "header.l_row.l_section h1.b_large-heading::text",
        "single_content": "section.l_row.m_content-article-standfirst .m_body-copy",
        "single_image": False,
        "single_date": "body .Site-body main header p.b_date",
        "single_date_format": "Updated: %d%m%Y",
        "single_tags": False,
        "deadline": ".m_body-copy span.l_blue",
        "deadline_format": "Deadline %d%m%Y",
        "apply_url": ".l_inner-grid a.b_submit.mod--next::attr(href)",
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "darpe",
        "orgs": "",
        "rubrique_website": "tender-and-grants",
        "default_pagination_limit": "",
        "themes": "technologie",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://darpe.me/tenders-and-grants/?keyword=&darpe_sector%5B%5D=18&search-dap=Search",
        "page_actu_loop": "https://darpe.me/tenders-and-grants/?keyword=&darpe_sector%5B%5D=18&search-dap=Search",
        "reg_ul": "table.table.table-striped",
        "reg_li": "tr",
        "reg_li_a": "td a",
        "reg_li_title": "td a::text",
        "reg_li_date": False,
        "reg_li_image": "td img::attr(src)",
        "single_title": ".blog-header h1::text",
        "single_content": False,
        "single_image": False,
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
        }

    test_model = {
        "batch_id": "dancing-opportunities",
        "orgs": "",
        "rubrique_website": "open-calls",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://dancingopportunities.com/category/open-calls/",
        "page_actu_loop": "https://dancingopportunities.com/category/open-calls/",
        "reg_ul": ".paginated_content",
        "reg_li": "article.post.type-post",
        "reg_li_a": ".post-content h2 a",
        "reg_li_title": ".post-content h2 a::text",
        "reg_li_date": ".post-meta.vcard span.updated",
        "reg_li_image": ".header img::attr(src)",
        "single_title": ".post-header h1.entry-title::text",
        "single_content": ".post-wrap .post-content.entry-content",
        "single_image": ".post-thumbnail.header img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": "p a::attr(href)",
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "china-residencies",
        "orgs": "",
        "rubrique_website": "residencies",
        "default_pagination_limit": "",
        "themes": "infrastructure",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://chinaresidencies.org/residencies/",
        "page_actu_loop": "https://chinaresidencies.org/residencies/",
        "reg_ul": "ul.grid.residencies",
        "reg_li": "li",
        "reg_li_a": "a",
        "reg_li_title": ".grid-item-caption.info.info-name::text",
        "reg_li_date": False,
        "reg_li_image": False,
        "single_title": ".banner-title h1::text",
        "single_content": "section.content",
        "single_image": False,
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "institut-francais-tunisie",
        "orgs": "",
        "rubrique_website": "open-calls;call-for-entry",
        "default_pagination_limit": "",
        "themes": "education",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://www.institutfrancais-tunisie.com/appels-projets/#/",
        "page_actu_loop": "https://www.institutfrancais-tunisie.com/appels-projets/#/",
        "reg_ul": ".quicktabs-tabpage",
        "reg_li": ".form-group",
        "reg_li_a": "span.field-content .views-field.views-field-title span a",
        "reg_li_title": "span.field-content .views-field.views-field-title span a::text",
        "reg_li_date": ".views-field.views-field-fieldset-1 span.field-content .views-field.views-field-published-at span.field-content time::attr(datetime)",
        "reg_li_image": ".views-field.views-field-fieldset span.field-content .views-field.views-field-field-image-appels a img::attr(img)",
        "single_title": "#header .titre_page h1 span::text",
        "single_content": "#detail-body .field.field--name-body.field--type-text-with-summary.field--label-hidden",
        "single_image": "#baniere .image_baniere.field.field--name-field-image-appels.field--type-image.field--label-hidden.field--item img",
        "single_date": "#detail-body .field.field--name-published-at.field--type-published-at time::attr(datetime)",
        "single_date_format": "%Y-%m-%d%H:%M",
        "single_tags": "#detail-body .field--name-field-mots-cles-appels.field--type-string",
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "institut-francais-maroc",
        "orgs": "",
        "rubrique_website": "open-calls;residencies",
        "default_pagination_limit": "",
        "themes": "education",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://if-maroc.org/projets/",
        "page_actu_loop": "https://if-maroc.org/projets/",
        "reg_ul": "#posts",
        "reg_li": "article",
        "reg_li_a": "a",
        "reg_li_title": "a::text",
        "reg_li_date": False,
        "reg_li_image": "a div img::attr(src)",
        "single_title": "#app main section.relative h1::text",
        "single_content": "#app main section.relative .post-content",
        "single_image": "#app main section.relative img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": "#app main section.relative p.mt-4",
        "deadline_format": "%d%F%Y",
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": "#app main section.relative a",
        "document_title": False
    }
    '''

    '''
    test_model = {
        "batch_id": "institut-francais-liban",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "education",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://institutfrancais-liban.com/evenements/liste/#/",
        "page_actu_loop": "https://institutfrancais-liban.com/evenements/liste/#/",
        "reg_ul": "#content .tribe-events-calendar-list",
        "reg_li": ".tribe-common-g-row.tribe-events-calendar-list__event-row",
        "reg_li_a": "a",
        "reg_li_title": "a::text",
        "reg_li_date": False,
        "reg_li_image": "a img::attr(src)",
        "single_title": "#tribe-events-content h1::text",
        "single_content": ".tribe-events-single-event-description.tribe-events-content",
        "single_image": "div.tribe-events-event-image img::attr(src)",
        "single_date": "div.tribe-events-single-section.tribe-events-event-meta.primary.tribe-clearfix dl dd abbr:attr(title)",
        "single_date_format": False,
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "institut-francais-syrie",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "education",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 144,
        "page_actu_home": "https://www.ifporient.org/",
        "page_actu_loop": "https://www.ifporient.org/page/ACTU_NBR/",
        "reg_ul": ".post-list.group",
        "reg_li": ".post-row article",
        "reg_li_a": "h2.post-title entry-title a",
        "reg_li_title": "h2.post-title entry-title a::text",
        "reg_li_date": False,
        "reg_li_image": ".post-thumbnail a img::attr(src)",
        "single_title": "#content article div h1::text",
        "single_content": "body .wp-embed .wp-embed-excerpt",
        "single_image": "body .wp-embed-featured-image.rectangular a img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "delegation-eu-tunisie",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 0,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://www.eeas.europa.eu/eeas/tenders_en",
        "page_actu_loop": "https://www.eeas.europa.eu/eeas/tenders_en?page=ACTU_NBR",
        "reg_ul": "#block-eeas-website-content section .view-content",
        "reg_li": ".card.node.node--type-tender",
        "reg_li_a": "h5.card-title a",
        "reg_li_title": "h5.card-title a::text",
        "reg_li_date": "time.datetime::attr(datetime)",
        "reg_li_image": False,
        "single_title": "#block-eeas-website-content article section .content-header h1.field.field--name-title::text",
        "single_content": "#block-eeas-website-content article section .info-text",
        "single_image": False,
        "single_date": "#block-eeas-website-content article section .content-header i",
        "single_date_format": "%d.%m.%Y",
        "single_tags": False,
        "deadline": "#block-eeas-website-content article section div.card div.side.deadline time::attr(datetime)",
        "deadline_format": "%Y-%m-%d%H:%M",
        "apply_url": False,
        "guess_apply_url_last_url": "#block-eeas-website-content article section .info-text a",
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
        "batch_id": "helvetia-tunisie",
        "orgs": "",
        "rubrique_website": "opportunities",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://www.ccsparis.com/evenements/?display=images",
        "page_actu_loop": "https://www.ccsparis.com/evenements/?display=images",
        "reg_ul": "main .lister--images",
        "reg_li": ".event",
        "reg_li_a": "a.event_link",
        "reg_li_title": ".event_informations .event_title",
        "reg_li_date": False,
        "reg_li_image": ".event_illustration .event_image picture img::attr(src)",
        "single_title": "body main .content div.content_title h1::text",
        "single_content": "body main div div.content div.content_center",
        "single_image": "body main div div.content div.content_center figure picture img::attr(src)",
        "single_date": False,
        "single_date_format": False,
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }

    test_model = {
         "batch_id": "transartists",
        "orgs": "",
        "rubrique_website": "open-calls",
        "default_pagination_limit": "",
        "themes": "culture",
        "lang": "FR",
        "loop_mode": "number_increase",
        "loop_start": 0,
        "loop_step": 1,
        "loop_end": 1,
        "page_actu_home": "https://www.transartists.org/en/transartists-calls?page=1",
        "page_actu_loop": "https://www.transartists.org/en/transartists-calls?page=ACTU_NBR",
        "reg_ul": "#block-views-block-news-block-1 .view-content table.table",
        "reg_li": "tr",
        "reg_li_a": "td.views-field-view-node h2 a",
        "reg_li_title": "td.views-field-view-node h2 a::text",
        "reg_li_date": False,
        "reg_li_image": "td.views-field-field-single-image article img::attr(src)",
        "single_title": ".node__content h2::text",
        "single_content": ".paragraph .field--name-field-paragraph-body",
        "single_image": ".field__item article .field.field--name-field-media-image.field--type-image.field--label-visually_hidden .field__item img::attr(src)",
        "single_date": "main article .field--type-datetime.field--label-hidden time:attr(datetime)",
        "single_date_format": "%Y-%m-%d%H:%M",
        "single_tags": False,
        "deadline": False,
        "deadline_format": False,
        "apply_url": False,
        "guess_apply_url_last_url": False,
        "eligibility_criteria": False,
        "document_url": False,
        "document_title": False
    }
    '''

    '''
    test_model = {
        "batch_id": "khaleejesque",
        "orgs": "",
        "rubrique_website": "culture",
        "default_pagination_limit": 1,
        "themes": "culture",
        "lang": "EN",
        "loop_mode": "number_increase",
        "loop_start": 1,
        "loop_step": 1,
        "loop_end": 16,
        "extraction_mode": "api", # html (default) / "api"
        "api_header_accept": "application/json, text/javascript, */*; q=0.01",
        "api_header_accept_language": 'fr-FR,fr;q=0.9',
        "api_header_content_type": 'application/x-www-form-urlencoded; charset=UTF-8',
        "api_header_origin": 'https://khaleejesque.me',
        "api_header_referer": 'https://khaleejesque.me/radar/',
        "api_header_request_with": 'XMLHttpRequest',
        "api_data_encode": True,
        "api_method": "POST",
        "api_endpoint": "https://khaleejesque.me/wp-admin/admin-ajax.php",
        "api_data": {
            'action': 'dtdr_generate_load_search_data_ouput',
            'current_page': 'ACTU_NBR',
            # 'offset': '20', # avoid useless calcs
            'type': 'type2',
            'gallery': 'featured_image',
            'post_per_page': '20',
            'columns': '3',
            'apply_isotope': 'true',
            'isotope_filter': '',
            'apply_child_of': 'false',
            'featured_items': 'false',
            'excerpt_length': '20',
            'features_image_or_icon': '',
            'features_include': '',
            'no_of_cat_to_display': '4',
            'apply_equal_height': 'false',
            'custom_options': '{"ad_items":"","ad_location":"listing","pricerange_start":"","pricerange_end":""}',
            'keyword': '',
            'user_latitude': '',
            'user_longitude': '',
            'use_radius': '',
            'radius': '',
            'radius_unit': '',
            'list_items': '',
            'categories': '',
            'tags': '',
            'cities': '',
            'neighborhood': '',
            'countystate': '',
            'countries': '',
            'ctype': '',
            'startdate': '',
            'pricerange_start': '',
            'pricerange_end': '',
            'features_query': '',
            'features_total_query': '',
            'sellers': '',
            'incharges': '',
            'orderby': '',
            'mls_number': '',
            'others': '',
            'load_data': 'true',
            'load_map': 'false',
            'listing_id': '49421',
            'listing_title': 'POPUP by COMFEST',
            'listing_permalink': 'https://khaleejesque.me/listings/popup-by-comfest/',
            'first_class': '',
            'loader': 'true',
            'loader_parent': '.dtdr-listing-output-data-container',
        },
        "api_nbr_key": "current_page",
        "api_result_type": "json",
        "api_result_key": "data",
        "api_loop_mode": "html", # html / json

        "page_actu_home": "https://khaleejesque.me/radar/",

        "page_actu_loop": False,
        "reg_ul": ".dtdr-listings-container .dtdr-listings-item-container",
        "reg_li": ".dtdr-column:not(.grid-sizer)",
        "reg_li_a": ".dtdr-listings-item-title a",
        "reg_li_title": ".dtdr-listings-item-title a::text",
        "reg_li_date": False,
        "reg_li_image": ".dtdr-listings-feature-image-holder img::attr(src)",
        "single_title": False,
        "single_content": ".elementor-widget-text-editor",
        "single_image": False,
        "single_date": "meta[property='og:article:published_time']::attr(content)",
        "single_date_format": "%Y-%m-%d%H:%M:%S",
        "single_tags": "ul.dtdr-listings-taxonomy-list li",
        "deadline": False,
        "deadline_format": False,
        "apply_url": "a.elementor-animation-grow",
        "document_url": False,
        "document_title": False
    }
    '''
    actuLib = ActuClass(
        config_dir = config_path,
        db_post_models_csv = config_path + '/post_models.csv',
        db_already_processed_posts_csv = config_path + '/processed_posts_urls.csv',
        db_already_processed_images_csv = config_path + '/processed_images_urls.csv',
        db_already_processed_publications_csv = config_path + '/processed_publications_urls.csv',
        should_use_same_session = False, # Force the usage of same session
        is_deep_scan_mode = True, # should scan all pages
        default_pagination_limit = 1, # should scan all pages
        debug_mode = False, # should debug test_model
        test_model = test_model,
        db_storage_csv = db_storage_csv,

        # handle auto images download
        should_save_image = False,
        db_storage_image = db_storage_image,

        # analytics
        enable_analytics= False,
        tracking_id= 'MO-XXXXX-X',
        tracking_domain= 'yourdomain.com',
    )

    newPosts = actuLib.extract_new_posts()

    actuLib.save_already_processed_items()
    actuLib.save_new_items()
    # actuLib.tag_all_posts()


if __name__ == "__main__":
    main()